name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app
        env:
          PAGES_DEPLOY_HOOK: ${{ secrets.CloudflarePagesDeployHook }}
        run: curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/$PAGES_DEPLOY_HOOK"
