# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Read .nvmrc
      run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
      id: nvmrc
    - name: Use Node.js $nvmrc
      uses: actions/setup-node@v2
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy app
        if: github.ref == 'refs/heads/master'
        env:
          PAGES_DEPLOY_HOOK: ${{ secrets.CloudflarePagesDeployHook }}
        run: curl -X POST "https://api.cloudflare.com/client/v4/pages/webhooks/deploy_hooks/$PAGES_DEPLOY_HOOK"
